// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Data;

#nullable disable

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231127121153_Product_To_Db")]
    partial class Product_To_Db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Electronics",
                            Description = "Samsun s23",
                            Name = "Mobile",
                            Price = 48925.5
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Utensils",
                            Description = "Prestige",
                            Name = "Pressure Cooker",
                            Price = 1892.0
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Movies",
                            Description = "Amazing spider man 2",
                            Name = "Spider Mna",
                            Price = 8925.5
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Electronics",
                            Description = "Iphone 13",
                            Name = "Mobile",
                            Price = 58925.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
